# Slimefun Custom addon by FN_FAL113, huge thanks to Walshy and Jeff (LiteXpansion) for letting me use their utils
# You can change the values here, it requires server restart to take effect.

# FN Power Xpansion Rank 1
FN-Xpansion-Rank1-Dayrate: 236
FN-Xpansion-Rank1-Nightrate: 138
FN-Xpansion-Rank1-Output: 20
FN-Xpansion-Rank1-Capacity: 600000

# FN Power Xpansion Rank 2
FN-Xpansion-Rank2-Dayrate: 472
FN-Xpansion-Rank2-Nightrate: 276
FN-Xpansion-Rank2-Output: 40
FN-Xpansion-Rank2-Capacity: 700000

# FN Power Xpansion Rank 3
FN-Xpansion-Rank3-Dayrate: 944
FN-Xpansion-Rank3-Nightrate: 552
FN-Xpansion-Rank3-Output: 60
FN-Xpansion-Rank3-Capacity: 800000

# FN Power Xpansion Rank 4
FN-Xpansion-Rank4-Dayrate: 1888
FN-Xpansion-Rank4-Nightrate: 1104
FN-Xpansion-Rank4-Output: 120
FN-Xpansion-Rank4-Capacity: 900000

# FN Power Xpansion Rank 5
FN-Xpansion-Rank5-Dayrate: 3776
FN-Xpansion-Rank5-Nightrate: 2208
FN-Xpansion-Rank5-Output: 240
FN-Xpansion-Rank5-Capacity: 1000000

# FN Power Xpansion Rank 6
FN-Xpansion-Rank6-Dayrate: 7552
FN-Xpansion-Rank6-Nightrate: 4416
FN-Xpansion-Rank6-Output: 480
FN-Xpansion-Rank6-Capacity: 1500000

# FN Power Xpansion Rank 7
FN-Xpansion-Rank7-Dayrate: 15104
FN-Xpansion-Rank7-Nightrate: 8832
FN-Xpansion-Rank7-Output: 960
FN-Xpansion-Rank7-Capacity: 2000000

# FN Power Xpansion Rank 8
FN-Xpansion-Rank8-Dayrate: 18880
FN-Xpansion-Rank8-Nightrate: 11040
FN-Xpansion-Rank8-Output: 1200
FN-Xpansion-Rank8-Capacity: 3000000

# FN Power Xpansion Rank 9
FN-Xpansion-Rank9-Dayrate: 22656
FN-Xpansion-Rank9-Nightrate: 13248
FN-Xpansion-Rank9-Output: 1440
FN-Xpansion-Rank9-Capacity: 4500000

# FN Power Xpansion Rank 10
FN-Xpansion-Rank10-Dayrate: 26432
FN-Xpansion-Rank10-Nightrate: 15456
FN-Xpansion-Rank10-Output: 1680
FN-Xpansion-Rank10-Capacity: 6750000

# FN Power Xpansion Rank 11
FN-Xpansion-Rank11-Dayrate: 30208
FN-Xpansion-Rank11-Nightrate: 17664
FN-Xpansion-Rank11-Output: 1920
FN-Xpansion-Rank11-Capacity: 9000000

# FN Power Xpansion Rank 12
FN-Xpansion-Rank12-Dayrate: 45312
FN-Xpansion-Rank12-Nightrate: 26496
FN-Xpansion-Rank12-Output: 2880
FN-Xpansion-Rank12-Capacity: 12000000