name: FNPowerXpansion
version: '${project.version}'
main: me.fnfal113.fnpowergenerators.FNPowerGenerators
api-version: 1.17
authors: [ FN_FAL113 ]
description: A custom slimefun addon
website: https://github.com/FN-FAL113
depend: [Slimefun]
softdepend:
  - LiteXpansion
